# ----------------------- #
#      User Configs       #
# ----------------------- #

name: Roberto Soares
title: Lead Consultant at <a href="http://www.thoughtworks.com/"><b>ThoughtWorks</b></a>
gravatar_email: roberto.tech@gmail.com
# don't forget to edit your "about" on _includes/about.md
# for more information about markdown, consider giving a look at some examples and basics in the follow urls:
# http://daringfireball.net/projects/markdown/basics
# http://en.wikipedia.org/wiki/Markdown


# ----------------------- #
#       Info Configs      #
# ----------------------- #

info:
  location: Porto Alegre
  code: JavaScript, TypeScript, Ruby, Elm, Haskell, Go
  company: ThoughtWorks
  university: UESC - Computer Science
  interests: Front-end, Open Source, Functional Proramming, Board games, Cycling
  email: contact@robertosoares.me

# ----------------------- #
#      Social Configs     #
# ----------------------- #

# Put your usernames here. Only usernames, without links.

social:
# Note about github: write down your_username/your_repository if you want to show a repository page, instead of your github account.
  github: roberto
  linkedin: rosoares
  facebook: 
  twitter: bt1
  foursquare:
  goodreads: 10822464-roberto
# Note about google+: Your googleplus username should be that huge number in your url (example: for https://plus.google.com/u/1/112176414644635750645/posts, your username is 112176414644635750645).
# For google+ pages, you may find this huge number written down 2 times. We only need it once.
  googleplus: 
  lastfm: 
  grooveshark: 
  rdio: 
  instagram: 
  flickr:
  quora:
  stackoverflow:
  rss:


# Now you should put your links.
# links:


# ----------------------- #
#      Project Configs    #
# ----------------------- #

# Google Analytics
google_analytics_tracking_id: UA-42001979-1

# Only make changes here if you _realy_ know what you're doing. Just an advice.

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']
