# ----------------------- #
#      User Configs       #
# ----------------------- #

name: Roberto Soares
title: Software Engineer at <a href="http://globo.com/">Globo.com</a>
location: Rio de Janeiro - Brazil
email: roberto.tech@gmail.com
gravatar_photo: false
# don't forget to edit your "about" on _includes/about.md
# for more information about markdown, consider giving a look at some examples and basics in the follow urls:
# http://daringfireball.net/projects/markdown/basics
# http://en.wikipedia.org/wiki/Markdown


# ----------------------- #
#      Social Configs     #
# ----------------------- #

# Put your usernames here. Only usernames, without links.

social:
  facebook: roberto.sof
  flickr:
  foursquare:
  github: roberto
  googleplus:
  lastfm:
  linkedin: rosoares
  quora:
  stackoverflow:
  twitter: AboutProject


# Now you should put your links.

links:
  -
    title: "Resume"
    url: "http://resume.linkedinlabs.com/k61po2u36"
  -
    title: "Working with Rails Profile"
    url: "http://workingwithrails.com/person/9376-roberto-soares"


# ----------------------- #
#      Project Configs    #
# ----------------------- #

# Only make changes here if you _realy_ know what you're doing. Just an advice.

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']
